repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, --show-fixes]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: uv run pytest --log-disable=test --durations=5  -m commit
        language: system
        types: [python]
        always_run: true
        pass_filenames: false